### ISSUE TITLE
E: Unable to correct problems, you have held broken packages Ubuntu 20.10 LTS 64 bit Linux

### ISSUE THREAD

**Issue by UbuntuEvangelist** [jookies/jasmin#1018]
I am using Ubuntu 20.10 LTS 64 bit Linux with python --version Python 3.8.10 but facing 

The following packages have unmet dependencies:
 jasmin-sms-gateway : Depends: python3-jookies-messaging but it is not installable
                      Depends: python3-txredisapi but it is not installable
                      Depends: python3-txamqp3 but it is not installable
                      Depends: python3-smpp-pdu3 but it is not installable
                      Depends: python3-smpp-twisted3 but it is not installable
E: Unable to correct problems, you have held broken packages.

![Screenshot from 2021-11-15 18-35-24](https://user-images.githubusercontent.com/1058663/141783210-f93013a0-fb1f-4ab1-8ae3-65901686494d.png)

**Comment by farirat** [comment]
Please test again, Jasmin 0.10.11 is now release to Ubuntu 20.04 to Ubuntu 22.04 (and RHEL 8)

**Comment by FlorentinCONGO** [comment]
> Please test again, Jasmin 0.10.11 is now release to Ubuntu 20.04 to Ubuntu 22.04 (and RHEL 8)

Hi, i tried to install Jasmin sms gateway but i can't. When i use the commands on https://docs.jasminsms.com/en/latest/installation/index.html#installation-prerequisites, i got: cannot find package jasmin-sms-gateway.
If i use this commands: `curl -s https://packagecloud.io/install/repositories/jookies/jasmin-sms-gateway/script.deb.sh | sudo bash` i got the message:
 ```
Paramétrage de python3-txredisapi (1.4.8) ...
ERROR: Could not find a version that satisfies the requirement txredisapi==1.4.8 (from versions: 0.2, 0.3, 0.5, 0.6, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.7)
ERROR: No matching distribution found for txredisapi==1.4.8
```
Could you help me please! 
Thanks in advance.

**Comment by magojr** [comment]
Not sure if it can solve your issue but I browse recently the repo: https://packagecloud.io/jookies/jasmin-sms-gateway/
And there is python3-txredisapi (1.4.8) .DEB package for 5 different ubuntu releases (focal, groovy, hirsute, impish, jammy).

The reported error seems to be a dependency issue caused by the install process, you probably miss the sh command that install the repo (or it give you another error). Anyway, consider to install the repo manually. 

I use RHEL so I don't know the exact place for apt repo but you should be able to find the place and add a new one.
For the content, in the script you mentioned there is the repo file based on dist and relesase, foe example: https://packagecloud.io/install/repositories/jookies/jasmin-sms-gateway/config_file.list?os=ubuntu&dist=hirsute&source=script

You may manually create the repo file copy-pating the content and you should go straight into the install process.

**Comment by AnythingLinux** [comment]
Try to use Ubuntu 20.04 LTS 64 bit Linux.
Install python 3.8.x version and set default python version.
Install pip pip 20.0.2 version and set default python version.
Install Python: https://gist.github.com/UbuntuEvangelist/fe805176e61d927d11b139166bdbfd6d
After install python 3.8.x version follow:

apt install python3-pip
cd
nano ~/.bashrc
# Add below to lines into the bottom of ~/.bashrc file
alias python=python3
alias pip=pip3
# Save & Exit ctrl+s and ctrl+x
alias python=python3
alias pip=pip3
source ~/.bashrc
sudo apt update
sudo apt upgrade -y
python --version
pip --version
pip install txredisapi
apt-get install python3-venv
apt install redis rabbitmq-server -y
pip install gunicorn
apt install pipx 
pipx install twisted --force
pipx ensurepath

curl -s https://packagecloud.io/install/repositories/jookies/jasmin-sms-gateway/script.deb.sh | sudo bash
apt-get install jasmin-sms-gateway
apt update -y && apt upgrade -y 

OR

curl -s https://setup.jasminsms.com/deb | sudo bash
apt install jasmin-sms-gateway
apt update -y && apt upgrade -y 

systemctl enable jasmind
systemctl start jasmind
systemctl status jasmind


# Contact telegram @LinuxGun for bulk sms gateway development using Jasmin SMS Gateway

**Comment by farirat** [comment]
> Try to use Ubuntu 20.04 LTS 64 bit Linux. Install python 3.8.x version and set default python version. Install pip pip 20.0.2 version and set default python version. Install Python: https://gist.github.com/UbuntuEvangelist/fe805176e61d927d11b139166bdbfd6d After install python 3.8.x version follow:
> 
> apt install python3-pip cd nano ~/.bashrc
> 
> # Add below to lines into the bottom of ~/.bashrc file
> alias python=python3 alias pip=pip3
> 
> # Save & Exit ctrl+s and ctrl+x
> alias python=python3 alias pip=pip3 source ~/.bashrc sudo apt update sudo apt upgrade -y python --version pip --version pip install txredisapi apt-get install python3-venv apt install redis rabbitmq-server -y pip install gunicorn apt install pipx pipx install twisted --force pipx ensurepath
> 
> curl -s https://packagecloud.io/install/repositories/jookies/jasmin-sms-gateway/script.deb.sh | sudo bash apt-get install jasmin-sms-gateway apt update -y && apt upgrade -y
> 
> OR
> 
> curl -s https://setup.jasminsms.com/deb | sudo bash apt install jasmin-sms-gateway apt update -y && apt upgrade -y
> 
> systemctl enable jasmind systemctl start jasmind systemctl status jasmind
> 
> # Contact telegram @linuxgun for bulk sms gateway development using Jasmin SMS Gateway

@UbuntuEvangelist please stop spamming.

**Comment by farirat** [comment]
@magojr & @FlorentinCONGO there were an issue in dependency packaging, it's fixed now.

**Comment by FlorentinCONGO** [comment]
Hi @magojr , @UbuntuEvangelist and @farirat, thanks for your help. I will try again.

**Comment by khandah** [comment]
I still have the same error E: Unable to locate package jasmin-sms-gateway
How can I solve that ?
Thank you.
